name: Core FE CD

on:
  schedule:
    # trigger everyday 01:00 am
    - cron: '0 1 * * *'

jobs:
  CD-Stage:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: core-FE-ci.yml
          workflow_conclusion: success
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Gitlab Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./web-app-artifact/apps/web-app/Dockerfile
          context: ./web-app-artifact
          push: true
          tags: ${{ vars.REGISTRY_HOST }}/${{ vars.REGISTRY_GROUP }}/${{ vars.REGISTRY_PROJECT_CORE_FE }}:${{ github.sha }}
