name: Core FE CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'apps/web-app/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'apps/web-app/**'

jobs:
  CI-Stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to project
        uses: actions/checkout@v3
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
      - name: Get pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install nodejs package
        run: pnpm install
      - name: Lint Stage
        run: pnpm lint:app
      - name: Test Stage
        run: pnpm test:app
      - name: Build Stage
        run: pnpm build:app
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: web-app-artifact
          path: | # default retention 90 days
            .
            !node_modules
