name: Core FE CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths:
    - apps/web-app

jobs:
  build-stage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g pnpm
    - run: pnpm install
    - run: pnpm lint-app
    - run: pnpm test-app
    - run: pnpm build-app
