name: Core BE CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'apps/web-api/**'
      - 'libs/model/**'
      - 'libs/nest/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'apps/web-api/**'
      - 'libs/model/**'
      - 'libs/nest/**'

jobs:
  CI-Stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to project
        uses: actions/checkout@v3
      - name: Get short sha
        uses: benjlevesque/short-sha@v2.1
        id: short-sha
        with:
          length: 7
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
      - name: Get pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install nodejs package
        run: pnpm install
      - name: Lint code
        run: pnpm lint:api
      - name: Test code
        run: pnpm test:api
      - name: Build production code
        run: pnpm build:api
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v3
        with:
          name: web-api-artifact-${{ steps.short-sha.outputs.sha }}
          path: |
            .
            !node_modules
