name: Core FE CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'apps/web-app/**'
  pull_request:
    branches:
      - 'master'
    # paths:
    #   - 'apps/web-app/**'

jobs:
  CI-Stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to project
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
      - name: Install package
        run: pnpm install
      - name: Lint Stage
        run: pnpm lint-app
      - name: Test Stage
        run: pnpm test-app
      - name: Build Stage
        run: pnpm build-app
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: web-app-artifact
          path: dist/web-app # default retention 90 days
