name: SonarCloud Coverage

on:
  push:
    branches:
      - 'master'
      - 'fix/sonar-coverage'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  SonarCloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
      - name: Install package
        run: pnpm install
      - name: Test and coverage
        run: pnpm jest --coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.MONOREPO_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
